GET http://localhost:8000/api/v1/
Content-Type: application/json

###

GET http://localhost:8000/api/v1/products/
Content-Type: application/json

###

GET http://localhost:8000/api/v1/products/?search=еный
Accept: application/json

###

GET http://localhost:8000/api/v1/stocks/
Accept: application/json

###

GET http://localhost:8000/api/v1/stocks/?products=6
Accept: application/json

###

POST http://localhost:8000/api/v1/products/
Accept: application/json

{
"title": "123",
"description": "Откручивать гайки"
}

###

DELETE http://localhost:8000/api/v1/stocks/8/
Accept: application/json

###

PATCH http://localhost:8000/api/v1/stocks/7/
Accept: application/json

{
  "address": "Европолис",
  "positions": [
    {
      "product": 8,
      "quantity": 40,
      "price": 24.00
    }
  ]
}






